CREATE TABLE IF NOT EXISTS sif_legacy_payment_projection (
    EXTERNAL_BANK_EVENT_ID VARCHAR(190) NOT NULL,
    NUM_FACT VARCHAR(64) NOT NULL,
    AMOUNT DECIMAL(12,2) NOT NULL,
    MOVEMENT_DATE DATE NOT NULL,
    PAYLOAD_HASH CHAR(64) NOT NULL,
    STATE ENUM('PENDING','APPLIED','FAILED') NOT NULL DEFAULT 'PENDING',
    ERROR_MESSAGE VARCHAR(500) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    APPLIED_AT DATETIME NULL,
    PRIMARY KEY (EXTERNAL_BANK_EVENT_ID),
    KEY IDX_SIF_LEGACY_PROJECTION_NUM_FACT (NUM_FACT),
    KEY IDX_SIF_LEGACY_PROJECTION_STATE (STATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
