<?php

return [
    'excerpt_window' => 3,
    'max_excerpts_per_source' => 30,
    'allowed_extensions' => ['md', 'php', 'sql', 'json', 'csv'],
    'blocked_prefixes' => ['.git', 'xat-original'],
    'blocked_patterns' => [
        '#(^|/)(parametres[-_ ]?connexio|\.env)([^/]*)$#iu',
        '#(^|/)(vendor|node_modules)/#iu',
    ],
    'defaults' => [
        [
            'id' => 'SRC-001',
            'path' => '00-control/registre-decisions.md',
            'role' => 'GOVERNANCE',
            'context' => 'OBJECTIU',
            'validation' => 'AUTORITZADA',
            'keywords' => ['fluxos fiscals especials', 'font de veritat', 'idempotencia'],
        ],
        [
            'id' => 'SRC-002',
            'path' => '00-control/estat-projecte.md',
            'role' => 'PROJECT_STATUS',
            'context' => 'IMPLEMENTACIO',
            'validation' => 'AUTORITZADA',
            'keywords' => ['Fluxos fiscals especials', 'DISSENY COBERT'],
        ],
        [
            'id' => 'SRC-003',
            'path' => 'documentacio/00-index-i-pla/documentacio-verifactu.md',
            'role' => 'MASTER_DESIGN',
            'context' => 'OBJECTIU',
            'validation' => 'AUTORITZADA',
            'keywords' => ['Accions fiscals possibles', 'previsualitzacio fiscal'],
        ],
        [
            'id' => 'SRC-018',
            'path' => 'documentacio/04-estat-final/33-casos-us-sif.md',
            'role' => 'USE_CASE_CATALOG',
            'context' => 'OBJECTIU',
            'validation' => 'CANDIDATA',
            'keywords' => ['UC-26', 'Criteri de completitud'],
        ],
    ],
    'cases' => [
        'UC-26' => [
            [
                'id' => 'SRC-004',
                'path' => 'documentacio/03-canvis-pendents/04-fluxos-facturacio.md',
                'role' => 'FUNCTIONAL_FLOW',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['Canvi de curs', 'CANVI_CURS_DIFERENCIA'],
            ],
            [
                'id' => 'SRC-005',
                'path' => 'documentacio/03-canvis-pendents/07-pantalles-intranet.md',
                'role' => 'SCREEN_DESIGN',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['Canvi de curs', 'previsualitzacio fiscal'],
            ],
            [
                'id' => 'SRC-006',
                'path' => 'documentacio/03-canvis-pendents/08-correus-i-plantilles.md',
                'role' => 'COMMUNICATIONS',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['Canvi de curs', 'diferencia de canvi de curs'],
            ],
            [
                'id' => 'SRC-007',
                'path' => 'documentacio/03-canvis-pendents/11-inventari-canvis-pendents.md',
                'role' => 'PENDING_CHANGE_INVENTORY',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['Canvis de curs', 'Descompte excepcional per canvi de curs'],
            ],
            [
                'id' => 'SRC-008',
                'path' => 'documentacio/04-estat-final/05-model-bd-sif.md',
                'role' => 'DATA_MODEL',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['canvi_curs', 'motiu_canvi', 'credit_balance'],
            ],
            [
                'id' => 'SRC-009',
                'path' => 'documentacio/04-estat-final/15-estat-final-sistema.md',
                'role' => 'FINAL_SYSTEM',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['Canvi de curs', 'Rectificativa'],
            ],
            [
                'id' => 'SRC-010',
                'path' => 'documentacio/04-estat-final/16-estat-final-pantalles.md',
                'role' => 'FINAL_SCREENS',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['Intranet - Canvi de curs', 'despeses de gestio'],
            ],
            [
                'id' => 'SRC-011',
                'path' => 'documentacio/04-estat-final/17-estat-final-bd-relacions.md',
                'role' => 'FINAL_RELATIONS',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['canvi_curs', 'factura_rectificacio', 'payment_allocation'],
            ],
            [
                'id' => 'SRC-012',
                'path' => 'documentacio/04-estat-final/18-estat-final-operacio-incidencies.md',
                'role' => 'OPERATIONS_AND_INCIDENTS',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['Baixes i canvis de curs', 'diferencia pendent'],
            ],
            [
                'id' => 'SRC-013',
                'path' => 'documentacio/05-governanca-operacio/20-pla-proves-validacio-sif.md',
                'role' => 'TEST_PLAN',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['canvi de curs amb diferencia', 'canvi de curs amb saldo'],
            ],
            [
                'id' => 'SRC-014',
                'path' => 'documentacio/05-governanca-operacio/21-seguretat-permisos-accessos.md',
                'role' => 'PERMISSIONS',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['Iniciar canvi de curs', 'validacio de servidor'],
            ],
            [
                'id' => 'SRC-015',
                'path' => 'documentacio/05-governanca-operacio/22-manual-operatiu-intern.md',
                'role' => 'OPERATING_PROCEDURE',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['canvi de curs', 'despeses de gestio'],
            ],
            [
                'id' => 'SRC-016',
                'path' => 'documentacio/05-governanca-operacio/24-diccionari-camps-i-valors.md',
                'role' => 'CONTROLLED_VALUES',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['CANVI_CURS', 'PENDING', 'RECTIFIED'],
            ],
            [
                'id' => 'SRC-017',
                'path' => 'documentacio/00-index-i-pla/26-matriu-cobertura-casos.md',
                'role' => 'COVERAGE_MATRIX',
                'context' => 'IMPLEMENTACIO',
                'validation' => 'AUTORITZADA',
                'keywords' => ['Canvi de curs', 'DISSENY COBERT'],
            ],
            [
                'id' => 'SRC-019',
                'path' => 'codi-drive/intranet-nova-canvis-verifactu/Intranet.php',
                'role' => 'HISTORICAL_CODE',
                'context' => 'HISTORIC',
                'validation' => 'OBSERVADA',
                'keywords' => ['modalCanviCurs', 'realitzarCanviCurs', 'updInscCanviCurs'],
            ],
            [
                'id' => 'SRC-020',
                'path' => 'documentacio/01-compliment-aeat/documentacio-sif-aeat.md',
                'role' => 'AEAT_COMPLIANCE',
                'context' => 'OBJECTIU',
                'validation' => 'AUTORITZADA',
                'keywords' => ['rectificativa', 'registre fiscal', 'inalterabilitat'],
            ],
            [
                'id' => 'SRC-021',
                'path' => 'sif/database/migrations/2026_09_15_000003_add_functional_audit_control.sql',
                'role' => 'DATABASE_MIGRATION',
                'context' => 'IMPLEMENTACIO',
                'validation' => 'AUTORITZADA',
                'keywords' => ['course_change_event', 'operational_event', 'MANAGEMENT_FEE'],
            ],
            [
                'id' => 'SRC-022',
                'path' => 'sif/src/Repository/OperationalEventRepository.php',
                'role' => 'IMPLEMENTED_COMPONENT',
                'context' => 'IMPLEMENTACIO',
                'validation' => 'AUTORITZADA',
                'keywords' => ['operational_event', 'fiscal_impact', 'correlation_id'],
            ],
            [
                'id' => 'SRC-023',
                'path' => 'sif/tests/Database/FunctionalAuditSchemaTest.php',
                'role' => 'IMPLEMENTATION_TEST',
                'context' => 'IMPLEMENTACIO',
                'validation' => 'AUTORITZADA',
                'keywords' => ['course_change_event', 'operational_event', 'append-only'],
            ],
        ],
    ],
];
