ALTER TABLE errors_verifactu
    ADD COLUMN UUID_INCIDENT CHAR(36) NULL AFTER ID,
    ADD COLUMN UUID_PAYMENT CHAR(36) NULL AFTER UUID_FACTURA,
    ADD COLUMN RESOURCE_TYPE VARCHAR(40) NULL AFTER UUID_PAYMENT,
    ADD COLUMN RESOURCE_ID VARCHAR(120) NULL AFTER RESOURCE_TYPE,
    ADD COLUMN SOURCE_TYPE VARCHAR(40) NULL AFTER RESOURCE_ID,
    ADD COLUMN SOURCE_ID VARCHAR(120) NULL AFTER SOURCE_TYPE,
    ADD COLUMN SEVERITY VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' AFTER TIPUS_INCIDENCIA,
    ADD COLUMN ASSIGNED_TO VARCHAR(120) NULL AFTER SEVERITY,
    ADD COLUMN CORRELATION_ID VARCHAR(120) NULL AFTER ASSIGNED_TO,
    ADD COLUMN IDEMPOTENCY_KEY VARCHAR(140) NULL AFTER CORRELATION_ID,
    ADD COLUMN IDEMPOTENCY_PAYLOAD_HASH CHAR(64) NULL AFTER IDEMPOTENCY_KEY,
    ADD COLUMN REASON_CODE VARCHAR(80) NULL AFTER IDEMPOTENCY_PAYLOAD_HASH,
    ADD COLUMN RESOLVED_AT DATETIME(6) NULL AFTER DETAILS,
    ADD COLUMN RESOLUTION_NOTES TEXT NULL AFTER RESOLVED_AT,
    ADD COLUMN CLOSURE_CRITERIA TEXT NULL AFTER RESOLUTION_NOTES,
    ADD UNIQUE KEY uq_errors_verifactu_uuid_incident (UUID_INCIDENT),
    ADD UNIQUE KEY uq_errors_verifactu_idempotency (IDEMPOTENCY_KEY),
    ADD KEY idx_errors_verifactu_payment (UUID_PAYMENT),
    ADD KEY idx_errors_verifactu_resource (RESOURCE_TYPE, RESOURCE_ID, ESTAT),
    ADD KEY idx_errors_verifactu_assignee (ASSIGNED_TO, ESTAT),
    ADD KEY idx_errors_verifactu_correlation (CORRELATION_ID, CREATED_AT);

ALTER TABLE sif_incident_action
    ADD COLUMN IDEMPOTENCY_KEY VARCHAR(140) NULL AFTER UUID_ACTION,
    ADD COLUMN PAYLOAD_HASH CHAR(64) NULL AFTER IDEMPOTENCY_KEY,
    ADD UNIQUE KEY uq_sif_incident_action_idempotency (IDEMPOTENCY_KEY);
