CREATE TABLE IF NOT EXISTS usoc_lifecycle_execution (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_EXECUTION CHAR(36) NOT NULL UNIQUE,
    REQUEST_ID VARCHAR(120) NOT NULL UNIQUE,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    ID_INSC BIGINT NOT NULL,
    IDPAG BIGINT NOT NULL,
    OPERATION VARCHAR(30) NOT NULL,
    STATE VARCHAR(30) NOT NULL,
    ACTOR_ID VARCHAR(120) NOT NULL,
    ACTOR_ROLES VARCHAR(255) NULL,
    REQUEST_HASH CHAR(64) NOT NULL,
    REQUEST_JSON JSON NOT NULL,
    PLAN_HASH CHAR(64) NOT NULL,
    PLAN_JSON JSON NOT NULL,
    RESULT_JSON JSON NULL,
    REVIEW_REASON VARCHAR(255) NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    COMPLETED_AT DATETIME(6) NULL,
    KEY idx_usoc_lifecycle_case (ID_INSC, IDPAG, CREATED_AT),
    KEY idx_usoc_lifecycle_state (STATE, CREATED_AT),
    CONSTRAINT chk_usoc_lifecycle_operation
        CHECK (OPERATION IN ('CANCELLATION')),
    CONSTRAINT chk_usoc_lifecycle_state
        CHECK (STATE IN ('REQUESTED', 'COMPLETED', 'REVIEW_REQUIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
