CREATE TABLE IF NOT EXISTS redsys_payment_intent (
    UUID_INTENT CHAR(36) NOT NULL PRIMARY KEY,
    DS_ORDER VARCHAR(40) NOT NULL,
    IDPAG INT NULL,
    SOURCE_TYPE VARCHAR(30) NOT NULL,
    SOURCE_ID VARCHAR(64) NULL,
    EXPECTED_AMOUNT DECIMAL(12,2) NOT NULL,
    CURRENCY CHAR(3) NOT NULL DEFAULT 'EUR',
    TERMINAL VARCHAR(20) NULL,
    SNAPSHOT_JSON JSON NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    CREATED_BY VARCHAR(100) NULL,
    EXPIRES_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY uq_redsys_intent_ds_order (DS_ORDER),
    KEY idx_redsys_intent_idpag (IDPAG),
    KEY idx_redsys_intent_source (SOURCE_TYPE, SOURCE_ID),
    KEY idx_redsys_intent_status (STATUS, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
