-- Persistent flow control for the single-issuer, serial AEAT worker.
CREATE TABLE IF NOT EXISTS aeat_worker_state (
    ID TINYINT NOT NULL PRIMARY KEY,
    NEXT_SEND_AT DATETIME NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
