CREATE TABLE IF NOT EXISTS factura (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_FACTURA CHAR(36) NOT NULL UNIQUE,
    IDEMPOTENCY_KEY VARCHAR(100) NOT NULL UNIQUE,
    TIPUS_SERIE CHAR(1) NOT NULL,
    ANY_FACT SMALLINT NOT NULL,
    NUM_SEQ INT NOT NULL,
    NUM_VISIBLE VARCHAR(30) NOT NULL UNIQUE,
    TIPUS_FACTURA VARCHAR(5) NOT NULL DEFAULT 'F1',
    DATA_EMISSIO DATETIME NOT NULL,
    DATA_OPERACIO DATETIME NULL,
    DATA_PAGAMENT DATETIME NULL,
    EMESA_ABANS_COBRAMENT TINYINT(1) NOT NULL DEFAULT 0,
    E_FACT TINYINT(1) NOT NULL DEFAULT 0,
    ESTAT_COBRAMENT VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ESTAT_FACTURA VARCHAR(20) NOT NULL DEFAULT 'ISSUED',
    ESTAT_AEAT VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    BILLING_NOM_RAO VARCHAR(180) NOT NULL,
    BILLING_NIF_CIF VARCHAR(20) NOT NULL,
    BILLING_ADRECA VARCHAR(180) NULL,
    BILLING_CP VARCHAR(10) NULL,
    BILLING_POBLACIO VARCHAR(120) NULL,
    BILLING_PROVINCIA VARCHAR(120) NULL,
    BILLING_PAIS CHAR(2) NOT NULL DEFAULT 'ES',
    BILLING_EMAIL VARCHAR(180) NULL,
    IMPORT_BASE DECIMAL(12,2) NOT NULL,
    DESC_IMPORT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    BASE_IMPOSABLE DECIMAL(12,2) NOT NULL,
    IVA_REGIM VARCHAR(20) NOT NULL DEFAULT 'EXEMPT',
    IVA_PCT DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    IVA_IMPORT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    TOTAL DECIMAL(12,2) NOT NULL,
    SOURCE_CHANNEL VARCHAR(30) NOT NULL,
    CREATED_BY VARCHAR(80) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_factura_num (TIPUS_SERIE, ANY_FACT, NUM_SEQ),
    KEY idx_factura_billing_nif (BILLING_NIF_CIF),
    KEY idx_factura_estat_cobrament (ESTAT_COBRAMENT),
    KEY idx_factura_estat_aeat (ESTAT_AEAT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factura_linia (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_FACTURA CHAR(36) NOT NULL,
    ORDRE INT NOT NULL,
    CONCEPTE VARCHAR(180) NOT NULL,
    DETALL TEXT NULL,
    QUANTITAT DECIMAL(12,2) NOT NULL DEFAULT 1.00,
    PREU_UNITARI DECIMAL(12,2) NOT NULL,
    IMPORT_BASE DECIMAL(12,2) NOT NULL,
    DESC_ORIGEN VARCHAR(30) NULL,
    DESC_MODE VARCHAR(30) NULL,
    DESC_ID BIGINT NULL,
    DESC_CODI_PROMO VARCHAR(80) NULL,
    DESC_PCT DECIMAL(5,2) NULL,
    DESC_IMPORT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    DESC_TEXT_VISIBLE VARCHAR(180) NULL,
    DESC_MOTIU_INTERN VARCHAR(255) NULL,
    BASE_IMPOSABLE DECIMAL(12,2) NOT NULL,
    IVA_REGIM VARCHAR(20) NOT NULL DEFAULT 'EXEMPT',
    IVA_PCT DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    IVA_IMPORT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    TOTAL DECIMAL(12,2) NOT NULL,
    SOURCE_TYPE VARCHAR(30) NULL,
    SOURCE_ID BIGINT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_factura_linia_ordre (UUID_FACTURA, ORDRE),
    KEY idx_linia_source (SOURCE_TYPE, SOURCE_ID),
    CONSTRAINT fk_linia_factura FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fiscal_sequence (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPUS_SERIE CHAR(1) NOT NULL,
    ANY_FACT SMALLINT NOT NULL,
    LAST_NUM INT NOT NULL DEFAULT 0,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_fiscal_sequence (TIPUS_SERIE, ANY_FACT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fiscal_chain_state (
    ID TINYINT PRIMARY KEY,
    LAST_FISCAL_ORDER BIGINT NOT NULL DEFAULT 0,
    LAST_HASH CHAR(64) NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factura_registres (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_FACTURA CHAR(36) NOT NULL,
    FISCAL_ORDER BIGINT NOT NULL UNIQUE,
    TIPUS_REGISTRE VARCHAR(20) NOT NULL DEFAULT 'ALTA',
    HASH_FACT CHAR(64) NOT NULL,
    HASH_FACT_ANT CHAR(64) NULL,
    PAYLOAD_JSON JSON NOT NULL,
    XML_PAYLOAD LONGTEXT NULL,
    AEAT_RESPONSE_JSON JSON NULL,
    ESTAT_AEAT VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_SENT DATETIME NULL,
    KEY idx_registre_factura (UUID_FACTURA),
    KEY idx_registre_hash_ant (HASH_FACT_ANT),
    CONSTRAINT fk_registre_factura FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factura_rectificacio (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_FACTURA_RECTIFICATIVA CHAR(36) NOT NULL,
    UUID_FACTURA_RECTIFICADA CHAR(36) NOT NULL,
    MOTIU VARCHAR(80) NOT NULL,
    MODE_RECTIFICACIO VARCHAR(30) NOT NULL,
    DETAILS TEXT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_rectificacio (UUID_FACTURA_RECTIFICATIVA, UUID_FACTURA_RECTIFICADA),
    CONSTRAINT fk_rectificativa_factura FOREIGN KEY (UUID_FACTURA_RECTIFICATIVA) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_rectificada_factura FOREIGN KEY (UUID_FACTURA_RECTIFICADA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_transaction (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_PAYMENT CHAR(36) NOT NULL UNIQUE,
    IDEMPOTENCY_KEY VARCHAR(120) NOT NULL UNIQUE,
    TIPUS_MOVIMENT VARCHAR(30) NOT NULL,
    METODE VARCHAR(30) NOT NULL,
    SOURCE_CHANNEL VARCHAR(30) NOT NULL,
    IMPORT DECIMAL(12,2) NOT NULL,
    DATA_MOVIMENT DATETIME NOT NULL,
    PROVIDER_REF VARCHAR(80) NULL,
    DS_ORDER VARCHAR(40) NULL,
    IDPAG INT NULL,
    REFERENCIA_BANCARIA VARCHAR(120) NULL,
    PAYLOAD_HASH CHAR(64) NOT NULL,
    ESTAT VARCHAR(30) NOT NULL DEFAULT 'CONFIRMED',
    NOTES TEXT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_payment_provider (PROVIDER_REF),
    KEY idx_payment_ds_order (DS_ORDER),
    KEY idx_payment_idpag (IDPAG),
    KEY idx_payment_date (DATA_MOVIMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_allocation (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_PAYMENT CHAR(36) NOT NULL,
    UUID_FACTURA CHAR(36) NOT NULL,
    IMPORT_ASSIGNAT DECIMAL(12,2) NOT NULL,
    TIPUS_ASSIGNACIO VARCHAR(30) NOT NULL DEFAULT 'INVOICE_PAYMENT',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_allocation_factura (UUID_FACTURA),
    CONSTRAINT fk_allocation_payment FOREIGN KEY (UUID_PAYMENT) REFERENCES payment_transaction(UUID_PAYMENT),
    CONSTRAINT fk_allocation_factura FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fact_rels (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_FACTURA CHAR(36) NOT NULL,
    FACTURA_RELACIONADA INT NULL,
    SOURCE_TYPE VARCHAR(30) NOT NULL,
    SOURCE_ID BIGINT NULL,
    RELATION_TYPE VARCHAR(30) NOT NULL DEFAULT 'ORIGIN',
    ID_FACTURA_LINIA BIGINT NULL,
    IDPAG INT NULL,
    DS_ORDER VARCHAR(40) NULL,
    VISIBLE_ALUMNE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_fact_rels_source (SOURCE_TYPE, SOURCE_ID),
    KEY idx_fact_rels_idpag (IDPAG),
    KEY idx_fact_rels_ds_order (DS_ORDER),
    KEY idx_fact_rels_factura_relacionada (FACTURA_RELACIONADA),
    CONSTRAINT fk_fact_rels_factura FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_fact_rels_linia FOREIGN KEY (ID_FACTURA_LINIA) REFERENCES factura_linia(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fiscal_queue (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_FACTURA CHAR(36) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    PAYLOAD_JSON JSON NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    ATTEMPTS INT NOT NULL DEFAULT 0,
    LAST_ERROR TEXT NULL,
    LOCKED_AT DATETIME NULL,
    SENT_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_queue_status (STATUS),
    KEY idx_queue_factura (UUID_FACTURA),
    CONSTRAINT fk_queue_factura FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factura_documents (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_FACTURA CHAR(36) NOT NULL,
    TIPUS VARCHAR(20) NOT NULL,
    PATH_FITXER VARCHAR(255) NOT NULL,
    HASH_FITXER CHAR(64) NOT NULL,
    ESTAT VARCHAR(30) NOT NULL DEFAULT 'CREATED',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_documents_factura (UUID_FACTURA),
    CONSTRAINT fk_documents_factura FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS redsys_notifications (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DS_ORDER VARCHAR(40) NOT NULL UNIQUE,
    IDPAG INT NULL,
    IMPORT DECIMAL(12,2) NOT NULL,
    RESPONSE_CODE VARCHAR(10) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    RAW_PAYLOAD_JSON JSON NULL,
    SIGNATURE_VALID TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_redsys_idpag (IDPAG),
    KEY idx_redsys_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS credit_balance (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_CREDIT CHAR(36) NOT NULL UNIQUE,
    HOLDER_TYPE VARCHAR(20) NOT NULL,
    HOLDER_ID INT NULL,
    HOLDER_NIF_CIF VARCHAR(20) NULL,
    HOLDER_NOM_RAO VARCHAR(180) NOT NULL,
    IMPORT_ORIGINAL DECIMAL(12,2) NOT NULL,
    IMPORT_DISPONIBLE DECIMAL(12,2) NOT NULL,
    SOURCE_TYPE VARCHAR(30) NOT NULL,
    SOURCE_ID BIGINT NULL,
    UUID_FACTURA_ORIGEN CHAR(36) NULL,
    UUID_FACTURA_RECTIFICATIVA CHAR(36) NULL,
    REVIEW_AFTER DATE NULL,
    ESTAT VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_credit_holder (HOLDER_TYPE, HOLDER_ID),
    KEY idx_credit_factura_origen (UUID_FACTURA_ORIGEN),
    KEY idx_credit_factura_rectificativa (UUID_FACTURA_RECTIFICATIVA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS errors_verifactu (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_FACTURA CHAR(36) NULL,
    TIPUS_INCIDENCIA VARCHAR(50) NOT NULL,
    ESTAT VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    DETAILS TEXT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_error_factura (UUID_FACTURA),
    KEY idx_error_estat (ESTAT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
