-- UC-010 · Governança de configuració i versió.
-- Migració additiva: no modifica cap migració ja aplicada.
--
-- Objectius:
--  * idempotència de l'alta de candidata i declaració;
--  * una única referència serialitzable a la versió activa;
--  * journal immutable d'activacions amb evidència del runtime observat.

ALTER TABLE sif_version
    ADD COLUMN IDEMPOTENCY_KEY VARCHAR(140) NULL,
    ADD COLUMN IDEMPOTENCY_PAYLOAD_HASH CHAR(64) NULL,
    ADD UNIQUE KEY uq_sif_version_idempotency (IDEMPOTENCY_KEY);

ALTER TABLE sif_declaration
    ADD COLUMN IDEMPOTENCY_KEY VARCHAR(140) NULL,
    ADD COLUMN IDEMPOTENCY_PAYLOAD_HASH CHAR(64) NULL,
    ADD UNIQUE KEY uq_sif_declaration_idempotency (IDEMPOTENCY_KEY);

CREATE TABLE IF NOT EXISTS sif_version_state (
    ID TINYINT NOT NULL PRIMARY KEY,
    ACTIVE_UUID_VERSION CHAR(36) NULL,
    LOCK_VERSION BIGINT NOT NULL DEFAULT 0,
    UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_sif_version_state_active
        FOREIGN KEY (ACTIVE_UUID_VERSION) REFERENCES sif_version(UUID_VERSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO sif_version_state (ID, ACTIVE_UUID_VERSION, LOCK_VERSION)
VALUES (1, NULL, 0);

CREATE TABLE IF NOT EXISTS sif_version_activation (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_ACTIVATION CHAR(36) NOT NULL UNIQUE,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    IDEMPOTENCY_PAYLOAD_HASH CHAR(64) NOT NULL,
    UUID_VERSION CHAR(36) NOT NULL,
    PREVIOUS_UUID_VERSION CHAR(36) NULL,
    UUID_DECLARATION CHAR(36) NOT NULL,
    UUID_BACKUP_EVIDENCE CHAR(36) NULL,
    ACTOR_ID VARCHAR(120) NOT NULL,
    ACTOR_ROLE VARCHAR(80) NOT NULL,
    REASON_CODE VARCHAR(80) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    ENVIRONMENT VARCHAR(30) NOT NULL,
    RUNTIME_GIT_REVISION CHAR(40) NOT NULL,
    RUNTIME_ARTIFACT_HASH CHAR(64) NOT NULL,
    RUNTIME_CONFIG_HASH CHAR(64) NOT NULL,
    RUNTIME_DATABASE_VERSION VARCHAR(80) NOT NULL,
    RUNTIME_EVIDENCE_JSON JSON NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVATED',
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_sif_version_activation_version (UUID_VERSION, CREATED_AT),
    KEY idx_sif_version_activation_correlation (CORRELATION_ID, CREATED_AT),
    CONSTRAINT fk_sif_version_activation_version
        FOREIGN KEY (UUID_VERSION) REFERENCES sif_version(UUID_VERSION),
    CONSTRAINT fk_sif_version_activation_previous
        FOREIGN KEY (PREVIOUS_UUID_VERSION) REFERENCES sif_version(UUID_VERSION),
    CONSTRAINT fk_sif_version_activation_declaration
        FOREIGN KEY (UUID_DECLARATION) REFERENCES sif_declaration(UUID_DECLARATION),
    CONSTRAINT fk_sif_version_activation_backup
        FOREIGN KEY (UUID_BACKUP_EVIDENCE) REFERENCES backup_restore_evidence(UUID_EVIDENCE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
