-- UC-012: durable debt-claim lifecycle.
-- Additive only: legacy inscription fields remain projections until cutover.

CREATE TABLE IF NOT EXISTS debt_claim_case (
    UUID_CLAIM CHAR(36) NOT NULL PRIMARY KEY,
    UUID_FACTURA CHAR(36) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    STAGE VARCHAR(30) NOT NULL DEFAULT 'DETECTED',
    OUTSTANDING_AMOUNT DECIMAL(12,2) NOT NULL,
    CURRENCY CHAR(3) NOT NULL DEFAULT 'EUR',
    RECIPIENT_TYPE VARCHAR(30) NOT NULL DEFAULT 'BILLING_PARTY',
    RECIPIENT_HASH CHAR(64) NULL,
    LOCK_VERSION BIGINT NOT NULL DEFAULT 1,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_BY VARCHAR(120) NULL,
    RESOLVED_AT DATETIME(6) NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_debt_claim_invoice (UUID_FACTURA),
    KEY idx_debt_claim_status (STATUS, STAGE, UPDATED_AT),
    KEY idx_debt_claim_correlation (CORRELATION_ID, UPDATED_AT),
    CONSTRAINT fk_debt_claim_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS debt_claim_event (
    UUID_EVENT CHAR(36) NOT NULL PRIMARY KEY,
    UUID_CLAIM CHAR(36) NOT NULL,
    ACTION VARCHAR(40) NOT NULL,
    RESULT VARCHAR(30) NOT NULL,
    FROM_STAGE VARCHAR(30) NULL,
    TO_STAGE VARCHAR(30) NOT NULL,
    OUTSTANDING_AMOUNT DECIMAL(12,2) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL,
    PAYLOAD_HASH CHAR(64) NOT NULL,
    REQUEST_ID VARCHAR(120) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    ACTOR_TYPE VARCHAR(30) NOT NULL,
    ACTOR_ID VARCHAR(120) NULL,
    ACTOR_ROLE VARCHAR(80) NULL,
    REASON_CODE VARCHAR(80) NOT NULL,
    UUID_NOTIFICATION CHAR(36) NULL,
    METADATA_JSON JSON NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    RECORDED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_debt_claim_event_idempotency (IDEMPOTENCY_KEY),
    KEY idx_debt_claim_event_claim (UUID_CLAIM, OCCURRED_AT),
    KEY idx_debt_claim_event_correlation (CORRELATION_ID, OCCURRED_AT),
    CONSTRAINT fk_debt_claim_event_case
        FOREIGN KEY (UUID_CLAIM) REFERENCES debt_claim_case(UUID_CLAIM),
    CONSTRAINT fk_debt_claim_event_notification
        FOREIGN KEY (UUID_NOTIFICATION) REFERENCES notification_outbox(UUID_NOTIFICATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
