CREATE TABLE IF NOT EXISTS enrollment_payment_flow_lock (
    SOURCE_TYPE VARCHAR(30) NOT NULL,
    SOURCE_ID BIGINT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (SOURCE_TYPE, SOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
