-- UC-016A / UC-016B. Durable lifecycle for post-issue group participant changes.
-- The execution journal separates academic mutation, fiscal correction and
-- economic effects so retries can resume without duplicating irreversible steps.

CREATE TABLE IF NOT EXISTS group_participant_change_execution (
    UUID_EXECUTION CHAR(36) NOT NULL PRIMARY KEY,
    IDEMPOTENCY_KEY VARCHAR(160) NOT NULL UNIQUE,
    CHANGE_TYPE VARCHAR(20) NOT NULL,
    UUID_FACTURA CHAR(36) NOT NULL,
    ID_INSC BIGINT NOT NULL,
    IDPAG BIGINT NULL,
    EXPECTED_FINGERPRINT CHAR(64) NOT NULL,
    DECISION_HASH CHAR(64) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CURRENT_STEP VARCHAR(50) NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    ACTOR_ID VARCHAR(100) NOT NULL,
    PLAN_JSON JSON NOT NULL,
    RESULT_JSON JSON NULL,
    ERROR_CODE VARCHAR(80) NULL,
    ERROR_MESSAGE VARCHAR(500) NULL,
    STARTED_AT DATETIME(6) NULL,
    COMPLETED_AT DATETIME(6) NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    KEY idx_group_change_invoice (UUID_FACTURA, ID_INSC),
    KEY idx_group_change_status (STATUS, UPDATED_AT),
    KEY idx_group_change_correlation (CORRELATION_ID),

    CONSTRAINT fk_group_change_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT chk_group_change_type CHECK (CHANGE_TYPE IN ('ADD', 'REMOVE')),
    CONSTRAINT chk_group_change_status CHECK (
        STATUS IN ('PLANNED', 'IN_PROGRESS', 'WAITING_EXTERNAL', 'COMPLETED', 'FAILED')
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS group_participant_change_step (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_EXECUTION CHAR(36) NOT NULL,
    STEP_NAME VARCHAR(50) NOT NULL,
    ORDRE INT NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(180) NOT NULL UNIQUE,
    INPUT_HASH CHAR(64) NOT NULL,
    RESULT_JSON JSON NULL,
    ERROR_CODE VARCHAR(80) NULL,
    ERROR_MESSAGE VARCHAR(500) NULL,
    STARTED_AT DATETIME(6) NULL,
    COMPLETED_AT DATETIME(6) NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),

    UNIQUE KEY uq_group_change_step (UUID_EXECUTION, STEP_NAME),
    KEY idx_group_change_step_status (STATUS, UPDATED_AT),

    CONSTRAINT fk_group_change_step_execution
        FOREIGN KEY (UUID_EXECUTION) REFERENCES group_participant_change_execution(UUID_EXECUTION),
    CONSTRAINT chk_group_change_step_status CHECK (
        STATUS IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED')
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
