-- Additive lifecycle model discovered while auditing the executable surfaces.
-- This migration does not replace legacy enrolment/product tables. It creates
-- the SIF-side records needed to stop inferring commercial, capacity,
-- entitlement, evidence, delivery and academic states from a single IDPAG.

CREATE TABLE IF NOT EXISTS commercial_operation_line (
    UUID_LINE CHAR(36) NOT NULL PRIMARY KEY,
    UUID_OPERATION CHAR(36) NOT NULL,
    PARENT_UUID_LINE CHAR(36) NULL,
    LINE_TYPE VARCHAR(30) NOT NULL,
    ORDRE INT NOT NULL,
    PRODUCT_TYPE VARCHAR(40) NOT NULL,
    PRODUCT_CODE VARCHAR(80) NULL,
    PRODUCT_EDITION VARCHAR(80) NULL,
    PARTICIPANT_PARTY_KEY VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    QUANTITY DECIMAL(12,2) NOT NULL DEFAULT 1.00,
    UNIT_PRICE DECIMAL(12,2) NOT NULL,
    GROSS_AMOUNT DECIMAL(12,2) NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    NET_AMOUNT DECIMAL(12,2) NOT NULL,
    TAX_REGIME VARCHAR(30) NOT NULL,
    TAX_RATE DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    TAX_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    EXEMPTION_OR_NON_SUBJECT_REASON VARCHAR(80) NULL,
    PRICE_RULE_VERSION VARCHAR(40) NOT NULL,
    SNAPSHOT_JSON JSON NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_commercial_operation_line_order (UUID_OPERATION, ORDRE),
    KEY idx_operation_line_product (PRODUCT_TYPE, PRODUCT_CODE, PRODUCT_EDITION),
    KEY idx_operation_line_parent (PARENT_UUID_LINE),
    CONSTRAINT fk_operation_line_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION),
    CONSTRAINT fk_operation_line_parent
        FOREIGN KEY (PARENT_UUID_LINE) REFERENCES commercial_operation_line(UUID_LINE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operation_line_invoice_link (
    UUID_LINE CHAR(36) NOT NULL,
    FACTURA_LINE_ID BIGINT NOT NULL,
    LINK_TYPE VARCHAR(30) NOT NULL DEFAULT 'MATERIALISED_AS',
    LINKED_AMOUNT DECIMAL(12,2) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (UUID_LINE, FACTURA_LINE_ID),
    KEY idx_operation_invoice_line (FACTURA_LINE_ID),
    CONSTRAINT fk_operation_invoice_link_operation_line
        FOREIGN KEY (UUID_LINE) REFERENCES commercial_operation_line(UUID_LINE),
    CONSTRAINT fk_operation_invoice_link_invoice_line
        FOREIGN KEY (FACTURA_LINE_ID) REFERENCES factura_linia(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS capacity_reservation (
    UUID_CAPACITY_RESERVATION CHAR(36) NOT NULL PRIMARY KEY,
    UUID_OPERATION CHAR(36) NOT NULL,
    UUID_LINE CHAR(36) NULL,
    RESOURCE_TYPE VARCHAR(30) NOT NULL,
    RESOURCE_KEY VARCHAR(120) NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    STATUS VARCHAR(30) NOT NULL,
    WAITLIST_POSITION INT NULL,
    EXPIRES_AT DATETIME NULL,
    CONFIRMED_AT DATETIME NULL,
    RELEASED_AT DATETIME NULL,
    RELEASE_REASON VARCHAR(120) NULL,
    LOCK_VERSION BIGINT NOT NULL DEFAULT 1,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_capacity_resource_status (RESOURCE_TYPE, RESOURCE_KEY, STATUS, EXPIRES_AT),
    KEY idx_capacity_operation (UUID_OPERATION),
    CONSTRAINT fk_capacity_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION),
    CONSTRAINT fk_capacity_operation_line
        FOREIGN KEY (UUID_LINE) REFERENCES commercial_operation_line(UUID_LINE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS discount_evidence (
    UUID_EVIDENCE CHAR(36) NOT NULL PRIMARY KEY,
    UUID_VALIDATION CHAR(36) NOT NULL,
    EVIDENCE_TYPE VARCHAR(40) NOT NULL,
    STORAGE_REF VARCHAR(255) NOT NULL,
    CONTENT_HASH CHAR(64) NOT NULL,
    MIME_TYPE VARCHAR(120) NOT NULL,
    SIZE_BYTES BIGINT NOT NULL,
    ACCESS_CLASSIFICATION VARCHAR(30) NOT NULL DEFAULT 'RESTRICTED',
    PURPOSE_CODE VARCHAR(60) NOT NULL,
    RETENTION_POLICY_CODE VARCHAR(60) NOT NULL,
    DELETE_AFTER DATETIME NULL,
    DELETED_AT DATETIME NULL,
    DELETION_PROOF_HASH CHAR(64) NULL,
    UPLOADED_BY VARCHAR(100) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_discount_evidence_content (UUID_VALIDATION, CONTENT_HASH),
    KEY idx_discount_evidence_retention (DELETE_AFTER, DELETED_AT),
    CONSTRAINT fk_discount_evidence_validation
        FOREIGN KEY (UUID_VALIDATION) REFERENCES discount_validation(UUID_VALIDATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_entitlement (
    UUID_ENTITLEMENT CHAR(36) NOT NULL PRIMARY KEY,
    ENTITLEMENT_TYPE VARCHAR(40) NOT NULL,
    CODE_HASH CHAR(64) NULL UNIQUE,
    HOLDER_PARTY_KEY VARCHAR(100) NOT NULL,
    ORIGIN_UUID_OPERATION CHAR(36) NULL,
    CONSUMED_UUID_OPERATION CHAR(36) NULL,
    RULE_VERSION VARCHAR(40) NOT NULL,
    RULE_SNAPSHOT_JSON JSON NOT NULL,
    FACE_VALUE DECIMAL(12,2) NULL,
    DISCOUNT_PERCENT DECIMAL(5,2) NULL,
    CURRENCY CHAR(3) NOT NULL DEFAULT 'EUR',
    STATUS VARCHAR(30) NOT NULL,
    ISSUED_AT DATETIME NOT NULL,
    EXPIRES_AT DATETIME NULL,
    RESERVED_AT DATETIME NULL,
    CONSUMED_AT DATETIME NULL,
    CANCELLED_AT DATETIME NULL,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_entitlement_holder_status (HOLDER_PARTY_KEY, STATUS, EXPIRES_AT),
    KEY idx_entitlement_origin (ORIGIN_UUID_OPERATION),
    CONSTRAINT fk_entitlement_origin_operation
        FOREIGN KEY (ORIGIN_UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION),
    CONSTRAINT fk_entitlement_consumed_operation
        FOREIGN KEY (CONSUMED_UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_entitlement_event (
    UUID_EVENT CHAR(36) NOT NULL PRIMARY KEY,
    UUID_ENTITLEMENT CHAR(36) NOT NULL,
    ACTION VARCHAR(30) NOT NULL,
    RESULT VARCHAR(30) NOT NULL,
    FROM_STATUS VARCHAR(30) NULL,
    TO_STATUS VARCHAR(30) NULL,
    UUID_OPERATION CHAR(36) NULL,
    ACTOR_TYPE VARCHAR(20) NOT NULL,
    ACTOR_ID VARCHAR(100) NULL,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    CAUSATION_ID VARCHAR(100) NULL,
    REASON_CODE VARCHAR(80) NULL,
    CHANGESET_JSON JSON NULL,
    OCCURRED_AT DATETIME NOT NULL,
    RECORDED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_entitlement_event_timeline (UUID_ENTITLEMENT, OCCURRED_AT),
    KEY idx_entitlement_event_correlation (CORRELATION_ID),
    CONSTRAINT fk_entitlement_event_entitlement
        FOREIGN KEY (UUID_ENTITLEMENT) REFERENCES commercial_entitlement(UUID_ENTITLEMENT),
    CONSTRAINT fk_entitlement_event_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS enrollment_import_run (
    UUID_IMPORT_RUN CHAR(36) NOT NULL PRIMARY KEY,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    SOURCE_CHANNEL VARCHAR(30) NOT NULL,
    SOURCE_STORAGE_REF VARCHAR(255) NULL,
    SOURCE_HASH CHAR(64) NOT NULL,
    FORMAT_VERSION VARCHAR(40) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TOTAL_ROWS INT NOT NULL DEFAULT 0,
    ACCEPTED_ROWS INT NOT NULL DEFAULT 0,
    REUSED_ROWS INT NOT NULL DEFAULT 0,
    REJECTED_ROWS INT NOT NULL DEFAULT 0,
    CREATED_BY VARCHAR(100) NOT NULL,
    STARTED_AT DATETIME NOT NULL,
    COMPLETED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_enrollment_import_status (STATUS, STARTED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS enrollment_import_item (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_IMPORT_RUN CHAR(36) NOT NULL,
    ROW_NUMBER INT NOT NULL,
    ROW_HASH CHAR(64) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    ERROR_CODE VARCHAR(80) NULL,
    ERROR_MESSAGE VARCHAR(500) NULL,
    SOURCE_ENROLLMENT_ID VARCHAR(100) NULL,
    UUID_OPERATION CHAR(36) NULL,
    RESULT_ENROLLMENT_ID VARCHAR(100) NULL,
    INPUT_SNAPSHOT_JSON JSON NOT NULL,
    RESULT_JSON JSON NULL,
    PROCESSED_AT DATETIME NULL,
    UNIQUE KEY uq_enrollment_import_row (UUID_IMPORT_RUN, ROW_NUMBER),
    UNIQUE KEY uq_enrollment_import_row_hash (UUID_IMPORT_RUN, ROW_HASH),
    KEY idx_enrollment_import_item_status (UUID_IMPORT_RUN, STATUS),
    CONSTRAINT fk_enrollment_import_item_run
        FOREIGN KEY (UUID_IMPORT_RUN) REFERENCES enrollment_import_run(UUID_IMPORT_RUN),
    CONSTRAINT fk_enrollment_import_item_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS master_data_change_request (
    UUID_CHANGE_REQUEST CHAR(36) NOT NULL PRIMARY KEY,
    ENTITY_TYPE VARCHAR(40) NOT NULL,
    ENTITY_KEY VARCHAR(120) NOT NULL,
    BASE_VERSION VARCHAR(40) NOT NULL,
    PROPOSED_VERSION VARCHAR(40) NOT NULL,
    CHANGESET_JSON JSON NOT NULL,
    AFFECTED_OPEN_OPERATIONS_JSON JSON NOT NULL,
    REASON_CODE VARCHAR(80) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    EFFECTIVE_AT DATETIME NULL,
    REQUESTED_BY VARCHAR(100) NOT NULL,
    REQUESTED_AT DATETIME NOT NULL,
    DECIDED_BY VARCHAR(100) NULL,
    DECIDED_AT DATETIME NULL,
    DECISION_REASON VARCHAR(500) NULL,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_master_data_change_version (ENTITY_TYPE, ENTITY_KEY, PROPOSED_VERSION),
    KEY idx_master_data_change_status (STATUS, EFFECTIVE_AT),
    KEY idx_master_data_change_correlation (CORRELATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS personal_data_change_request (
    UUID_PERSONAL_CHANGE_REQUEST CHAR(36) NOT NULL PRIMARY KEY,
    SUBJECT_KEY VARCHAR(100) NOT NULL,
    REQUESTER_ACTOR_ID VARCHAR(100) NOT NULL,
    CHANGESET_JSON JSON NOT NULL,
    JUSTIFICATION TEXT NULL,
    EVIDENCE_STORAGE_REF VARCHAR(255) NULL,
    EVIDENCE_HASH CHAR(64) NULL,
    STATUS VARCHAR(30) NOT NULL,
    REVIEWED_BY VARCHAR(100) NULL,
    REVIEWED_AT DATETIME NULL,
    REJECTION_REASON VARCHAR(500) NULL,
    PROPAGATION_STATUS VARCHAR(30) NULL,
    PROPAGATION_RESULT_JSON JSON NULL,
    AFFECTED_OPEN_OPERATIONS_JSON JSON NULL,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    REQUESTED_AT DATETIME NOT NULL,
    COMPLETED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_personal_change_subject (SUBJECT_KEY, STATUS, REQUESTED_AT),
    KEY idx_personal_change_correlation (CORRELATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS electronic_invoice_delivery (
    UUID_DELIVERY CHAR(36) NOT NULL PRIMARY KEY,
    UUID_FACTURA CHAR(36) NOT NULL,
    FACTURA_DOCUMENT_ID BIGINT NOT NULL,
    FORMAT_CODE VARCHAR(40) NOT NULL,
    FORMAT_VERSION VARCHAR(40) NOT NULL,
    RECIPIENT_ADDRESS_HASH CHAR(64) NOT NULL,
    CHANNEL VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    ATTEMPT_COUNT INT NOT NULL DEFAULT 0,
    NEXT_RETRY_AT DATETIME NULL,
    FIRST_ATTEMPT_AT DATETIME NULL,
    DELIVERED_AT DATETIME NULL,
    LAST_ERROR_CODE VARCHAR(80) NULL,
    LAST_ERROR_MESSAGE VARCHAR(500) NULL,
    DELIVERY_PROOF_STORAGE_REF VARCHAR(255) NULL,
    DELIVERY_PROOF_HASH CHAR(64) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_einvoice_delivery_invoice (UUID_FACTURA, STATUS),
    KEY idx_einvoice_delivery_retry (STATUS, NEXT_RETRY_AT),
    CONSTRAINT fk_einvoice_delivery_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_einvoice_delivery_document
        FOREIGN KEY (FACTURA_DOCUMENT_ID) REFERENCES factura_documents(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS academic_economic_state_event (
    UUID_EVENT CHAR(36) NOT NULL PRIMARY KEY,
    ENROLLMENT_KEY VARCHAR(100) NOT NULL,
    UUID_OPERATION CHAR(36) NULL,
    PARTICIPANT_PARTY_KEY VARCHAR(100) NULL,
    ACTION VARCHAR(40) NOT NULL,
    RESULT VARCHAR(30) NOT NULL,
    ACADEMIC_STATE_BEFORE VARCHAR(40) NULL,
    ACADEMIC_STATE_AFTER VARCHAR(40) NULL,
    ACCESS_STATE_BEFORE VARCHAR(40) NULL,
    ACCESS_STATE_AFTER VARCHAR(40) NULL,
    ECONOMIC_STATE_SNAPSHOT VARCHAR(40) NOT NULL,
    ECONOMIC_SNAPSHOT_HASH CHAR(64) NOT NULL,
    RULE_VERSION VARCHAR(40) NOT NULL,
    ACTOR_TYPE VARCHAR(20) NOT NULL,
    ACTOR_ID VARCHAR(100) NULL,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    CAUSATION_ID VARCHAR(100) NULL,
    REASON_CODE VARCHAR(80) NULL,
    METADATA_JSON JSON NULL,
    OCCURRED_AT DATETIME NOT NULL,
    RECORDED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_academic_economic_enrollment (ENROLLMENT_KEY, OCCURRED_AT),
    KEY idx_academic_economic_operation (UUID_OPERATION, OCCURRED_AT),
    KEY idx_academic_economic_correlation (CORRELATION_ID),
    CONSTRAINT fk_academic_economic_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
