CREATE TABLE IF NOT EXISTS sif_audit_event (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_EVENT CHAR(36) NOT NULL UNIQUE,
    REQUEST_ID VARCHAR(120) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CAUSATION_ID VARCHAR(120) NULL,
    ACTION VARCHAR(80) NOT NULL,
    RESULT VARCHAR(30) NOT NULL,
    RESOURCE_TYPE VARCHAR(50) NOT NULL,
    RESOURCE_ID VARCHAR(120) NULL,
    SOURCE_ENVIRONMENT VARCHAR(30) NOT NULL,
    SOURCE_CHANNEL VARCHAR(30) NOT NULL,
    ACTOR_TYPE VARCHAR(30) NOT NULL,
    ACTOR_ID VARCHAR(120) NULL,
    ACTOR_ROLE VARCHAR(80) NULL,
    REASON_CODE VARCHAR(80) NULL,
    BEFORE_HASH CHAR(64) NULL,
    AFTER_HASH CHAR(64) NULL,
    CHANGESET_JSON JSON NULL,
    ERROR_CODE VARCHAR(80) NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    RECORDED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_sif_audit_correlation (CORRELATION_ID, RECORDED_AT),
    KEY idx_sif_audit_resource (RESOURCE_TYPE, RESOURCE_ID, RECORDED_AT),
    KEY idx_sif_audit_actor (ACTOR_TYPE, ACTOR_ID, RECORDED_AT),
    KEY idx_sif_audit_result (RESULT, RECORDED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_action_event (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_EVENT CHAR(36) NOT NULL UNIQUE,
    UUID_PAYMENT CHAR(36) NULL,
    PAYMENT_IDEMPOTENCY_KEY VARCHAR(120) NULL,
    REQUEST_ID VARCHAR(120) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CAUSATION_ID VARCHAR(120) NULL,
    ACTION VARCHAR(80) NOT NULL,
    RESULT VARCHAR(30) NOT NULL,
    IS_TERMINAL TINYINT(1) NOT NULL DEFAULT 0,
    SOURCE_ENVIRONMENT VARCHAR(30) NOT NULL,
    SOURCE_CHANNEL VARCHAR(30) NOT NULL,
    ACTOR_TYPE VARCHAR(30) NOT NULL,
    ACTOR_ID VARCHAR(120) NULL,
    ACTOR_ROLE VARCHAR(80) NULL,
    REASON_CODE VARCHAR(80) NULL,
    BEFORE_HASH CHAR(64) NULL,
    AFTER_HASH CHAR(64) NULL,
    CHANGESET_JSON JSON NULL,
    ERROR_CODE VARCHAR(80) NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    RECORDED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_payment_action_payment (UUID_PAYMENT, RECORDED_AT),
    KEY idx_payment_action_idempotency (PAYMENT_IDEMPOTENCY_KEY, RECORDED_AT),
    KEY idx_payment_action_correlation (CORRELATION_ID, RECORDED_AT),
    KEY idx_payment_action_request (REQUEST_ID, RECORDED_AT),
    KEY idx_payment_action_unfinished (IS_TERMINAL, RESULT, RECORDED_AT),
    CONSTRAINT fk_payment_action_payment
        FOREIGN KEY (UUID_PAYMENT) REFERENCES payment_transaction(UUID_PAYMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS operational_event (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_OPERATIONAL_EVENT CHAR(36) NOT NULL UNIQUE,
    OPERATION_TYPE VARCHAR(80) NOT NULL,
    SOURCE_TYPE VARCHAR(50) NOT NULL,
    SOURCE_ID VARCHAR(120) NULL,
    UUID_FACTURA CHAR(36) NULL,
    UUID_PAYMENT CHAR(36) NULL,
    FISCAL_IMPACT VARCHAR(30) NOT NULL DEFAULT 'PENDING_CLASSIFICATION',
    ECONOMIC_IMPACT VARCHAR(30) NOT NULL DEFAULT 'NONE',
    STATUS VARCHAR(30) NOT NULL DEFAULT 'RECORDED',
    REASON_CODE VARCHAR(80) NOT NULL,
    BEFORE_SNAPSHOT_JSON JSON NULL,
    AFTER_SNAPSHOT_JSON JSON NULL,
    BEFORE_HASH CHAR(64) NULL,
    AFTER_HASH CHAR(64) NULL,
    ACTOR_TYPE VARCHAR(30) NOT NULL,
    ACTOR_ID VARCHAR(120) NULL,
    ACTOR_ROLE VARCHAR(80) NULL,
    SOURCE_CHANNEL VARCHAR(30) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    RECORDED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_operational_source (SOURCE_TYPE, SOURCE_ID, RECORDED_AT),
    KEY idx_operational_invoice (UUID_FACTURA, RECORDED_AT),
    KEY idx_operational_payment (UUID_PAYMENT, RECORDED_AT),
    KEY idx_operational_correlation (CORRELATION_ID, RECORDED_AT),
    CONSTRAINT fk_operational_factura
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_operational_payment
        FOREIGN KEY (UUID_PAYMENT) REFERENCES payment_transaction(UUID_PAYMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS billing_profile_history (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_PROFILE_VERSION CHAR(36) NOT NULL UNIQUE,
    SUBJECT_TYPE VARCHAR(30) NOT NULL,
    SUBJECT_ID VARCHAR(120) NOT NULL,
    VERSION_NO INT NOT NULL,
    BILLING_SNAPSHOT_JSON JSON NOT NULL,
    SNAPSHOT_HASH CHAR(64) NOT NULL,
    VALID_FROM DATETIME(6) NOT NULL,
    VALID_TO DATETIME(6) NULL,
    CHANGE_REASON VARCHAR(255) NOT NULL,
    ACTOR_ID VARCHAR(120) NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_billing_profile_version (SUBJECT_TYPE, SUBJECT_ID, VERSION_NO),
    KEY idx_billing_profile_current (SUBJECT_TYPE, SUBJECT_ID, VALID_TO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS course_change_event (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_CHANGE CHAR(36) NOT NULL UNIQUE,
    UUID_OPERATIONAL_EVENT CHAR(36) NOT NULL,
    SOURCE_ENROLLMENT_ID BIGINT NOT NULL,
    TARGET_ENROLLMENT_ID BIGINT NULL,
    SOURCE_COURSE_ID BIGINT NOT NULL,
    TARGET_COURSE_ID BIGINT NOT NULL,
    ORIGINAL_AMOUNT DECIMAL(12,2) NOT NULL,
    TARGET_AMOUNT DECIMAL(12,2) NOT NULL,
    MANAGEMENT_FEE DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    DIFFERENCE_AMOUNT DECIMAL(12,2) NOT NULL,
    DISCOUNT_SNAPSHOT_JSON JSON NULL,
    ECONOMIC_DECISION VARCHAR(40) NOT NULL,
    FISCAL_DECISION VARCHAR(40) NOT NULL,
    UUID_RESULT_INVOICE CHAR(36) NULL,
    UUID_RESULT_PAYMENT CHAR(36) NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_course_change_source (SOURCE_ENROLLMENT_ID),
    KEY idx_course_change_target (TARGET_ENROLLMENT_ID),
    CONSTRAINT fk_course_change_operational
        FOREIGN KEY (UUID_OPERATIONAL_EVENT) REFERENCES operational_event(UUID_OPERATIONAL_EVENT),
    CONSTRAINT fk_course_change_invoice
        FOREIGN KEY (UUID_RESULT_INVOICE) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_course_change_payment
        FOREIGN KEY (UUID_RESULT_PAYMENT) REFERENCES payment_transaction(UUID_PAYMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS enrollment_cancellation_event (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_CANCELLATION CHAR(36) NOT NULL UNIQUE,
    UUID_OPERATIONAL_EVENT CHAR(36) NOT NULL,
    ENROLLMENT_ID BIGINT NOT NULL,
    CANCELLATION_REASON VARCHAR(80) NOT NULL,
    EFFECTIVE_AT DATETIME(6) NOT NULL,
    ECONOMIC_DECISION VARCHAR(40) NOT NULL,
    RETURN_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    CREDIT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    NON_RETURN_REASON VARCHAR(255) NULL,
    FISCAL_DECISION VARCHAR(40) NOT NULL,
    UUID_RECTIFYING_INVOICE CHAR(36) NULL,
    UUID_REFUND_PAYMENT CHAR(36) NULL,
    UUID_CREDIT CHAR(36) NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_cancellation_enrollment (ENROLLMENT_ID, EFFECTIVE_AT),
    CONSTRAINT fk_cancellation_operational
        FOREIGN KEY (UUID_OPERATIONAL_EVENT) REFERENCES operational_event(UUID_OPERATIONAL_EVENT),
    CONSTRAINT fk_cancellation_invoice
        FOREIGN KEY (UUID_RECTIFYING_INVOICE) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_cancellation_payment
        FOREIGN KEY (UUID_REFUND_PAYMENT) REFERENCES payment_transaction(UUID_PAYMENT),
    CONSTRAINT fk_cancellation_credit
        FOREIGN KEY (UUID_CREDIT) REFERENCES credit_balance(UUID_CREDIT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS factura_registre_control (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACTURA_REGISTRE_ID BIGINT NOT NULL UNIQUE,
    PREVIOUS_REGISTRE_ID BIGINT NULL,
    RECORD_ACTION VARCHAR(30) NOT NULL,
    CORRECTION_KIND VARCHAR(40) NULL,
    REJECTION_PREVIOUS TINYINT(1) NOT NULL DEFAULT 0,
    WITHOUT_PREVIOUS_RECORD TINYINT(1) NOT NULL DEFAULT 0,
    XML_HASH CHAR(64) NULL,
    GENERATOR_VERSION VARCHAR(80) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_registre_control_previous (PREVIOUS_REGISTRE_ID),
    KEY idx_registre_control_action (RECORD_ACTION, CREATED_AT),
    CONSTRAINT fk_registre_control_record
        FOREIGN KEY (FACTURA_REGISTRE_ID) REFERENCES factura_registres(ID),
    CONSTRAINT fk_registre_control_previous
        FOREIGN KEY (PREVIOUS_REGISTRE_ID) REFERENCES factura_registres(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS aeat_submission_attempt (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_ATTEMPT CHAR(36) NOT NULL UNIQUE,
    FACTURA_REGISTRE_ID BIGINT NOT NULL,
    FISCAL_QUEUE_ID BIGINT NULL,
    ATTEMPT_NO INT NOT NULL,
    ENVIRONMENT VARCHAR(20) NOT NULL,
    ENDPOINT_CODE VARCHAR(80) NOT NULL,
    REQUEST_HASH CHAR(64) NOT NULL,
    RESPONSE_HTTP_CODE INT NULL,
    RESPONSE_CODE VARCHAR(80) NULL,
    RESPONSE_CSV VARCHAR(120) NULL,
    RESPONSE_JSON JSON NULL,
    STATUS VARCHAR(30) NOT NULL,
    ERROR_CODE VARCHAR(80) NULL,
    ERROR_DETAIL TEXT NULL,
    STARTED_AT DATETIME(6) NOT NULL,
    FINISHED_AT DATETIME(6) NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_aeat_attempt (FACTURA_REGISTRE_ID, ATTEMPT_NO),
    KEY idx_aeat_attempt_status (STATUS, CREATED_AT),
    KEY idx_aeat_attempt_queue (FISCAL_QUEUE_ID),
    CONSTRAINT fk_aeat_attempt_record
        FOREIGN KEY (FACTURA_REGISTRE_ID) REFERENCES factura_registres(ID),
    CONSTRAINT fk_aeat_attempt_queue
        FOREIGN KEY (FISCAL_QUEUE_ID) REFERENCES fiscal_queue(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS document_job (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_JOB CHAR(36) NOT NULL UNIQUE,
    UUID_FACTURA CHAR(36) NOT NULL,
    DOCUMENT_TYPE VARCHAR(20) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    GENERATOR_VERSION VARCHAR(80) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    ATTEMPTS INT NOT NULL DEFAULT 0,
    MAX_ATTEMPTS INT NOT NULL DEFAULT 5,
    LOCKED_AT DATETIME(6) NULL,
    NEXT_ATTEMPT_AT DATETIME(6) NULL,
    FACTURA_DOCUMENT_ID BIGINT NULL,
    STORAGE_KEY VARCHAR(255) NULL,
    OUTPUT_HASH CHAR(64) NULL,
    LAST_ERROR TEXT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    FINISHED_AT DATETIME(6) NULL,
    KEY idx_document_job_status (STATUS, NEXT_ATTEMPT_AT),
    KEY idx_document_job_invoice (UUID_FACTURA, DOCUMENT_TYPE),
    CONSTRAINT fk_document_job_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_document_job_document
        FOREIGN KEY (FACTURA_DOCUMENT_ID) REFERENCES factura_documents(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_outbox (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_NOTIFICATION CHAR(36) NOT NULL UNIQUE,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    TEMPLATE_CODE VARCHAR(80) NOT NULL,
    TEMPLATE_VERSION VARCHAR(40) NOT NULL,
    RECIPIENT_TYPE VARCHAR(30) NOT NULL,
    RECIPIENT_HASH CHAR(64) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    UUID_FACTURA CHAR(36) NULL,
    UUID_PAYMENT CHAR(36) NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    NEXT_ATTEMPT_AT DATETIME(6) NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    SENT_AT DATETIME(6) NULL,
    KEY idx_notification_status (STATUS, NEXT_ATTEMPT_AT),
    KEY idx_notification_invoice (UUID_FACTURA, CREATED_AT),
    KEY idx_notification_payment (UUID_PAYMENT, CREATED_AT),
    CONSTRAINT fk_notification_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_notification_payment
        FOREIGN KEY (UUID_PAYMENT) REFERENCES payment_transaction(UUID_PAYMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_delivery_attempt (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_DELIVERY_ATTEMPT CHAR(36) NOT NULL UNIQUE,
    UUID_NOTIFICATION CHAR(36) NOT NULL,
    ATTEMPT_NO INT NOT NULL,
    CHANNEL VARCHAR(30) NOT NULL,
    PROVIDER_REF VARCHAR(120) NULL,
    STATUS VARCHAR(30) NOT NULL,
    ERROR_CODE VARCHAR(80) NULL,
    ERROR_DETAIL TEXT NULL,
    STARTED_AT DATETIME(6) NOT NULL,
    FINISHED_AT DATETIME(6) NULL,
    UNIQUE KEY uq_notification_attempt (UUID_NOTIFICATION, ATTEMPT_NO),
    KEY idx_notification_attempt_status (STATUS, STARTED_AT),
    CONSTRAINT fk_notification_attempt_outbox
        FOREIGN KEY (UUID_NOTIFICATION) REFERENCES notification_outbox(UUID_NOTIFICATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fiscal_document_access (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_ACCESS CHAR(36) NOT NULL UNIQUE,
    FACTURA_DOCUMENT_ID BIGINT NULL,
    UUID_FACTURA CHAR(36) NOT NULL,
    ACTION VARCHAR(30) NOT NULL,
    RESULT VARCHAR(30) NOT NULL,
    TOKEN_FINGERPRINT CHAR(64) NULL,
    ACTOR_TYPE VARCHAR(30) NOT NULL,
    ACTOR_ID VARCHAR(120) NULL,
    ACTOR_ROLE VARCHAR(80) NULL,
    SOURCE_CHANNEL VARCHAR(30) NOT NULL,
    REQUEST_ID VARCHAR(120) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    REASON_CODE VARCHAR(80) NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    RECORDED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_document_access_document (FACTURA_DOCUMENT_ID, RECORDED_AT),
    KEY idx_document_access_invoice (UUID_FACTURA, RECORDED_AT),
    KEY idx_document_access_actor (ACTOR_TYPE, ACTOR_ID, RECORDED_AT),
    CONSTRAINT fk_document_access_document
        FOREIGN KEY (FACTURA_DOCUMENT_ID) REFERENCES factura_documents(ID),
    CONSTRAINT fk_document_access_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sif_incident_action (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_ACTION CHAR(36) NOT NULL UNIQUE,
    INCIDENT_ID BIGINT NOT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    PREVIOUS_STATUS VARCHAR(30) NULL,
    NEW_STATUS VARCHAR(30) NOT NULL,
    SEVERITY VARCHAR(20) NOT NULL,
    ASSIGNEE_ID VARCHAR(120) NULL,
    ACTOR_ID VARCHAR(120) NULL,
    ACTOR_ROLE VARCHAR(80) NULL,
    REASON_CODE VARCHAR(80) NOT NULL,
    DETAILS TEXT NULL,
    EVIDENCE_JSON JSON NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_incident_action_incident (INCIDENT_ID, CREATED_AT),
    KEY idx_incident_action_assignee (ASSIGNEE_ID, NEW_STATUS),
    CONSTRAINT fk_incident_action_incident
        FOREIGN KEY (INCIDENT_ID) REFERENCES errors_verifactu(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sif_version (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_VERSION CHAR(36) NOT NULL UNIQUE,
    VERSION_CODE VARCHAR(80) NOT NULL UNIQUE,
    GIT_REVISION CHAR(40) NOT NULL,
    ARTIFACT_HASH CHAR(64) NOT NULL,
    CONFIG_HASH CHAR(64) NOT NULL,
    DATABASE_VERSION VARCHAR(80) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    CREATED_BY VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ACTIVATED_AT DATETIME(6) NULL,
    KEY idx_sif_version_status (STATUS, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sif_declaration (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_DECLARATION CHAR(36) NOT NULL UNIQUE,
    UUID_VERSION CHAR(36) NOT NULL,
    DECLARATION_VERSION VARCHAR(40) NOT NULL,
    DOCUMENT_HASH CHAR(64) NOT NULL,
    STORAGE_KEY VARCHAR(255) NOT NULL,
    APPROVED_BY VARCHAR(120) NOT NULL,
    APPROVED_AT DATETIME(6) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_declaration_version (UUID_VERSION, DECLARATION_VERSION),
    CONSTRAINT fk_declaration_version
        FOREIGN KEY (UUID_VERSION) REFERENCES sif_version(UUID_VERSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fiscal_export (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_EXPORT CHAR(36) NOT NULL UNIQUE,
    EXPORT_TYPE VARCHAR(40) NOT NULL,
    FILTERS_JSON JSON NOT NULL,
    REQUESTED_BY VARCHAR(120) NOT NULL,
    REQUESTED_ROLE VARCHAR(80) NOT NULL,
    REASON_CODE VARCHAR(80) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    STORAGE_KEY VARCHAR(255) NULL,
    FILE_HASH CHAR(64) NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    FINISHED_AT DATETIME(6) NULL,
    KEY idx_fiscal_export_status (STATUS, CREATED_AT),
    KEY idx_fiscal_export_requester (REQUESTED_BY, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fiscal_export_access (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_ACCESS CHAR(36) NOT NULL UNIQUE,
    UUID_EXPORT CHAR(36) NOT NULL,
    ACTION VARCHAR(30) NOT NULL,
    RESULT VARCHAR(30) NOT NULL,
    ACTOR_ID VARCHAR(120) NOT NULL,
    ACTOR_ROLE VARCHAR(80) NOT NULL,
    REQUEST_ID VARCHAR(120) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    RECORDED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_export_access_export (UUID_EXPORT, RECORDED_AT),
    CONSTRAINT fk_export_access_export
        FOREIGN KEY (UUID_EXPORT) REFERENCES fiscal_export(UUID_EXPORT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reconciliation_run (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_RUN CHAR(36) NOT NULL UNIQUE,
    RECONCILIATION_TYPE VARCHAR(50) NOT NULL,
    SOURCE_SYSTEM VARCHAR(40) NOT NULL,
    INPUT_HASH CHAR(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
    STARTED_BY VARCHAR(120) NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    STARTED_AT DATETIME(6) NOT NULL,
    FINISHED_AT DATETIME(6) NULL,
    SUMMARY_JSON JSON NULL,
    KEY idx_reconciliation_status (STATUS, STARTED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reconciliation_item (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_ITEM CHAR(36) NOT NULL UNIQUE,
    UUID_RUN CHAR(36) NOT NULL,
    ITEM_TYPE VARCHAR(40) NOT NULL,
    SOURCE_REFERENCE VARCHAR(120) NULL,
    UUID_FACTURA CHAR(36) NULL,
    UUID_PAYMENT CHAR(36) NULL,
    RESULT VARCHAR(30) NOT NULL,
    DIFFERENCE_CODE VARCHAR(80) NULL,
    DIFFERENCE_JSON JSON NULL,
    RESOLUTION_STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    RESOLUTION_ACTION VARCHAR(80) NULL,
    RESOLVED_BY VARCHAR(120) NULL,
    RESOLVED_AT DATETIME(6) NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_reconciliation_item_run (UUID_RUN, RESULT),
    KEY idx_reconciliation_item_invoice (UUID_FACTURA),
    KEY idx_reconciliation_item_payment (UUID_PAYMENT),
    CONSTRAINT fk_reconciliation_item_run
        FOREIGN KEY (UUID_RUN) REFERENCES reconciliation_run(UUID_RUN),
    CONSTRAINT fk_reconciliation_item_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_reconciliation_item_payment
        FOREIGN KEY (UUID_PAYMENT) REFERENCES payment_transaction(UUID_PAYMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS backup_restore_evidence (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_EVIDENCE CHAR(36) NOT NULL UNIQUE,
    OPERATION_TYPE VARCHAR(20) NOT NULL,
    ENVIRONMENT VARCHAR(20) NOT NULL,
    SCOPE_JSON JSON NOT NULL,
    BACKUP_REFERENCE VARCHAR(255) NOT NULL,
    BACKUP_HASH CHAR(64) NULL,
    STATUS VARCHAR(30) NOT NULL,
    RPO_MINUTES INT NULL,
    RTO_MINUTES INT NULL,
    INTEGRITY_RESULT VARCHAR(30) NULL,
    EXECUTED_BY VARCHAR(120) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    STARTED_AT DATETIME(6) NOT NULL,
    FINISHED_AT DATETIME(6) NULL,
    EVIDENCE_JSON JSON NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_backup_evidence_type (OPERATION_TYPE, STARTED_AT),
    KEY idx_backup_evidence_status (STATUS, STARTED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fact_rels_context (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACT_RELS_ID BIGINT NOT NULL UNIQUE,
    UUID_OPERATIONAL_EVENT CHAR(36) NULL,
    RELATION_REASON VARCHAR(80) NOT NULL,
    VISIBILITY_REASON VARCHAR(255) NOT NULL,
    CREATED_BY VARCHAR(120) NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_fact_rels_context_relation
        FOREIGN KEY (FACT_RELS_ID) REFERENCES fact_rels(ID),
    CONSTRAINT fk_fact_rels_context_operational
        FOREIGN KEY (UUID_OPERATIONAL_EVENT) REFERENCES operational_event(UUID_OPERATIONAL_EVENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
