CREATE TABLE IF NOT EXISTS internal_api_request (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    REQUEST_ID CHAR(36) NOT NULL,
    KEY_ID VARCHAR(80) NOT NULL,
    ACTOR_ID VARCHAR(120) NOT NULL,
    ACTOR_ROLES VARCHAR(500) NOT NULL,
    HTTP_METHOD VARCHAR(12) NOT NULL,
    REQUEST_PATH VARCHAR(255) NOT NULL,
    BODY_HASH CHAR(64) NOT NULL,
    REQUESTED_AT DATETIME NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_internal_api_request_id (REQUEST_ID),
    KEY idx_internal_api_actor (ACTOR_ID, RECORDED_AT),
    KEY idx_internal_api_recorded (RECORDED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
