CREATE TABLE IF NOT EXISTS debt_claim_case (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_CLAIM CHAR(36) NOT NULL UNIQUE,
    UUID_FACTURA CHAR(36) NOT NULL UNIQUE,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    CURRENT_STAGE VARCHAR(40) NOT NULL DEFAULT 'DETECTED',
    VERSION_NO INT NOT NULL DEFAULT 0,
    OUTSTANDING_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    RECIPIENT_TYPE VARCHAR(30) NULL,
    RECIPIENT_HASH CHAR(64) NULL,
    LAST_EVENT_AT DATETIME(6) NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    KEY idx_debt_claim_status (STATUS, CURRENT_STAGE, UPDATED_AT),
    CONSTRAINT fk_debt_claim_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS debt_claim_event (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_CLAIM_EVENT CHAR(36) NOT NULL UNIQUE,
    UUID_CLAIM CHAR(36) NOT NULL,
    UUID_FACTURA CHAR(36) NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    PAYLOAD_HASH CHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    OUTSTANDING_BEFORE DECIMAL(12,2) NOT NULL,
    OUTSTANDING_AFTER DECIMAL(12,2) NOT NULL,
    RECIPIENT_TYPE VARCHAR(30) NULL,
    RECIPIENT_HASH CHAR(64) NULL,
    REASON_CODE VARCHAR(80) NOT NULL,
    ACTOR_TYPE VARCHAR(30) NOT NULL,
    ACTOR_ID VARCHAR(120) NULL,
    ACTOR_ROLE VARCHAR(80) NULL,
    SOURCE_CHANNEL VARCHAR(30) NOT NULL,
    REQUEST_ID VARCHAR(120) NOT NULL,
    CORRELATION_ID VARCHAR(120) NOT NULL,
    PAYLOAD_JSON JSON NOT NULL,
    OCCURRED_AT DATETIME(6) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_debt_claim_event_version (UUID_CLAIM, VERSION_NO),
    KEY idx_debt_claim_event_invoice (UUID_FACTURA, CREATED_AT),
    KEY idx_debt_claim_event_claim (UUID_CLAIM, CREATED_AT),
    KEY idx_debt_claim_event_correlation (CORRELATION_ID, CREATED_AT),
    CONSTRAINT fk_debt_claim_event_case
        FOREIGN KEY (UUID_CLAIM) REFERENCES debt_claim_case(UUID_CLAIM),
    CONSTRAINT fk_debt_claim_event_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
