CREATE TABLE IF NOT EXISTS usoc_financing_case (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_CASE CHAR(36) NOT NULL UNIQUE,
    ID_INSC BIGINT NOT NULL,
    IDPAG BIGINT NOT NULL,
    UUID_STUDENT_INVOICE CHAR(36) NOT NULL,
    UUID_ENTITY_INVOICE CHAR(36) NULL,
    STUDENT_AMOUNT DECIMAL(12,2) NOT NULL,
    ENTITY_AMOUNT DECIMAL(12,2) NOT NULL,
    STUDENT_PAYMENT_STATUS VARCHAR(30) NOT NULL DEFAULT 'PAID',
    ENTITY_PAYMENT_STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    STATUS VARCHAR(40) NOT NULL DEFAULT 'PENDING_ENTITY_INVOICE',
    CORRELATION_ID VARCHAR(120) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_usoc_case_inscription_payment (ID_INSC, IDPAG),
    UNIQUE KEY uq_usoc_case_student_invoice (UUID_STUDENT_INVOICE),
    UNIQUE KEY uq_usoc_case_entity_invoice (UUID_ENTITY_INVOICE),
    KEY idx_usoc_case_status (STATUS, UPDATED_AT),
    CONSTRAINT fk_usoc_case_student_invoice
        FOREIGN KEY (UUID_STUDENT_INVOICE) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_usoc_case_entity_invoice
        FOREIGN KEY (UUID_ENTITY_INVOICE) REFERENCES factura(UUID_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
