ALTER TABLE notification_outbox
    ADD COLUMN ATTEMPTS INT NOT NULL DEFAULT 0 AFTER STATUS,
    ADD COLUMN MAX_ATTEMPTS INT NOT NULL DEFAULT 5 AFTER ATTEMPTS,
    ADD COLUMN LOCKED_AT DATETIME(6) NULL AFTER MAX_ATTEMPTS,
    ADD COLUMN LOCKED_BY VARCHAR(120) NULL AFTER LOCKED_AT,
    ADD COLUMN CLAIM_TOKEN CHAR(36) NULL AFTER LOCKED_BY,
    ADD COLUMN LAST_ERROR TEXT NULL AFTER NEXT_ATTEMPT_AT,
    ADD COLUMN CANCELLED_AT DATETIME(6) NULL AFTER SENT_AT,
    ADD KEY idx_notification_claim (STATUS, NEXT_ATTEMPT_AT, LOCKED_AT),
    ADD KEY idx_notification_claim_token (CLAIM_TOKEN);
