-- Additive controls found in the third executable-surface audit.
-- These records keep consent, identity, edition, address and Moodle/Prisma
-- reconciliation separate from invoices and payment transactions.

CREATE TABLE IF NOT EXISTS communication_consent (
    UUID_CONSENT CHAR(36) NOT NULL PRIMARY KEY,
    SUBJECT_KEY VARCHAR(100) NOT NULL,
    PURPOSE_CODE VARCHAR(60) NOT NULL,
    CHANNEL VARCHAR(30) NOT NULL,
    SCOPE_CODE VARCHAR(60) NOT NULL,
    NOTICE_VERSION VARCHAR(40) NOT NULL,
    LAWFUL_BASIS VARCHAR(40) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    SOURCE_SYSTEM VARCHAR(40) NOT NULL,
    SOURCE_REFERENCE VARCHAR(120) NULL,
    CAPTURED_AT DATETIME NOT NULL,
    WITHDRAWN_AT DATETIME NULL,
    EXPIRES_AT DATETIME NULL,
    CURRENT_EVENT_UUID CHAR(36) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_communication_consent_scope (SUBJECT_KEY, PURPOSE_CODE, CHANNEL, SCOPE_CODE),
    KEY idx_communication_consent_status (STATUS, PURPOSE_CODE, CHANNEL),
    KEY idx_communication_consent_subject (SUBJECT_KEY, CAPTURED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS communication_consent_event (
    UUID_EVENT CHAR(36) NOT NULL PRIMARY KEY,
    UUID_CONSENT CHAR(36) NOT NULL,
    ACTION VARCHAR(30) NOT NULL,
    RESULT VARCHAR(30) NOT NULL,
    FROM_STATUS VARCHAR(30) NULL,
    TO_STATUS VARCHAR(30) NOT NULL,
    NOTICE_VERSION VARCHAR(40) NOT NULL,
    EVIDENCE_HASH CHAR(64) NOT NULL,
    ACTOR_TYPE VARCHAR(20) NOT NULL,
    ACTOR_ID VARCHAR(100) NULL,
    SOURCE_SYSTEM VARCHAR(40) NOT NULL,
    SOURCE_REFERENCE VARCHAR(120) NULL,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    REASON_CODE VARCHAR(80) NULL,
    METADATA_JSON JSON NULL,
    OCCURRED_AT DATETIME NOT NULL,
    RECORDED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_consent_event_timeline (UUID_CONSENT, OCCURRED_AT),
    KEY idx_consent_event_correlation (CORRELATION_ID),
    CONSTRAINT fk_consent_event_consent
        FOREIGN KEY (UUID_CONSENT) REFERENCES communication_consent(UUID_CONSENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE communication_consent
    ADD CONSTRAINT fk_communication_consent_current_event
        FOREIGN KEY (CURRENT_EVENT_UUID) REFERENCES communication_consent_event(UUID_EVENT);

CREATE TABLE IF NOT EXISTS external_identity_link (
    UUID_IDENTITY_LINK CHAR(36) NOT NULL PRIMARY KEY,
    SUBJECT_KEY VARCHAR(100) NOT NULL,
    SYSTEM_CODE VARCHAR(40) NOT NULL,
    EXTERNAL_ID VARCHAR(120) NOT NULL,
    IDENTITY_TYPE VARCHAR(40) NOT NULL,
    NORMALIZED_EMAIL_HASH CHAR(64) NULL,
    NORMALIZED_DOCUMENT_HASH CHAR(64) NULL,
    STATUS VARCHAR(30) NOT NULL,
    VERIFIED_AT DATETIME NULL,
    VERIFIED_BY VARCHAR(100) NULL,
    VALID_FROM DATETIME NOT NULL,
    VALID_TO DATETIME NULL,
    SNAPSHOT_HASH CHAR(64) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_external_identity (SYSTEM_CODE, EXTERNAL_ID, IDENTITY_TYPE),
    KEY idx_external_identity_subject (SUBJECT_KEY, SYSTEM_CODE, STATUS),
    KEY idx_external_identity_document (NORMALIZED_DOCUMENT_HASH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS identity_conflict_case (
    UUID_IDENTITY_CONFLICT CHAR(36) NOT NULL PRIMARY KEY,
    SUBJECT_KEY VARCHAR(100) NULL,
    CONFLICT_TYPE VARCHAR(50) NOT NULL,
    SOURCE_SYSTEM VARCHAR(40) NOT NULL,
    SOURCE_REFERENCE VARCHAR(120) NULL,
    CANDIDATE_IDENTITIES_JSON JSON NOT NULL,
    IMPACTED_OPERATIONS_JSON JSON NULL,
    STATUS VARCHAR(30) NOT NULL,
    DECISION VARCHAR(40) NULL,
    DECISION_REASON VARCHAR(500) NULL,
    REQUESTED_BY VARCHAR(100) NOT NULL,
    REQUESTED_AT DATETIME NOT NULL,
    RESOLVED_BY VARCHAR(100) NULL,
    RESOLVED_AT DATETIME NULL,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_identity_conflict_status (STATUS, REQUESTED_AT),
    KEY idx_identity_conflict_subject (SUBJECT_KEY, STATUS),
    KEY idx_identity_conflict_correlation (CORRELATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS edition_lifecycle_event (
    UUID_EDITION_EVENT CHAR(36) NOT NULL PRIMARY KEY,
    PRODUCT_TYPE VARCHAR(40) NOT NULL,
    PRODUCT_CODE VARCHAR(80) NOT NULL,
    PRODUCT_EDITION VARCHAR(80) NOT NULL,
    ACTION VARCHAR(30) NOT NULL,
    RESULT VARCHAR(30) NOT NULL,
    STATUS_BEFORE VARCHAR(30) NULL,
    STATUS_AFTER VARCHAR(30) NOT NULL,
    EFFECTIVE_AT DATETIME NOT NULL,
    REASON_CODE VARCHAR(80) NOT NULL,
    AFFECTED_OPERATION_COUNT INT NOT NULL DEFAULT 0,
    AFFECTED_RESERVATION_COUNT INT NOT NULL DEFAULT 0,
    ACTOR_ID VARCHAR(100) NOT NULL,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    SNAPSHOT_BEFORE_HASH CHAR(64) NULL,
    SNAPSHOT_AFTER_HASH CHAR(64) NOT NULL,
    METADATA_JSON JSON NULL,
    OCCURRED_AT DATETIME NOT NULL,
    RECORDED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_edition_lifecycle_edition (PRODUCT_TYPE, PRODUCT_CODE, PRODUCT_EDITION, OCCURRED_AT),
    KEY idx_edition_lifecycle_correlation (CORRELATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS edition_operation_impact (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_EDITION_EVENT CHAR(36) NOT NULL,
    UUID_OPERATION CHAR(36) NOT NULL,
    UUID_CAPACITY_RESERVATION CHAR(36) NULL,
    IMPACT_TYPE VARCHAR(40) NOT NULL,
    REQUIRED_ACTION VARCHAR(40) NOT NULL,
    ECONOMIC_DECISION VARCHAR(40) NULL,
    FISCAL_DECISION VARCHAR(40) NULL,
    STATUS VARCHAR(30) NOT NULL,
    RESULT_JSON JSON NULL,
    RESOLVED_BY VARCHAR(100) NULL,
    RESOLVED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_edition_operation_impact (UUID_EDITION_EVENT, UUID_OPERATION),
    KEY idx_edition_operation_status (STATUS, REQUIRED_ACTION),
    CONSTRAINT fk_edition_impact_event
        FOREIGN KEY (UUID_EDITION_EVENT) REFERENCES edition_lifecycle_event(UUID_EDITION_EVENT),
    CONSTRAINT fk_edition_impact_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION),
    CONSTRAINT fk_edition_impact_reservation
        FOREIGN KEY (UUID_CAPACITY_RESERVATION) REFERENCES capacity_reservation(UUID_CAPACITY_RESERVATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS address_validation_case (
    UUID_ADDRESS_VALIDATION CHAR(36) NOT NULL PRIMARY KEY,
    SUBJECT_KEY VARCHAR(100) NULL,
    UUID_OPERATION CHAR(36) NULL,
    ADDRESS_ROLE VARCHAR(30) NOT NULL,
    SOURCE_SYSTEM VARCHAR(40) NOT NULL,
    SOURCE_REFERENCE VARCHAR(120) NULL,
    ORIGINAL_ADDRESS_JSON JSON NOT NULL,
    ORIGINAL_ADDRESS_HASH CHAR(64) NOT NULL,
    NORMALIZED_ADDRESS_JSON JSON NULL,
    NORMALIZATION_RULE_VERSION VARCHAR(40) NULL,
    STATUS VARCHAR(30) NOT NULL,
    REQUESTED_AT DATETIME NOT NULL,
    REVIEWED_BY VARCHAR(100) NULL,
    REVIEWED_AT DATETIME NULL,
    DECISION_REASON VARCHAR(500) NULL,
    PROPAGATION_RESULT_JSON JSON NULL,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_address_validation_source (SOURCE_SYSTEM, SOURCE_REFERENCE, ORIGINAL_ADDRESS_HASH),
    KEY idx_address_validation_status (STATUS, REQUESTED_AT),
    KEY idx_address_validation_subject (SUBJECT_KEY, STATUS),
    CONSTRAINT fk_address_validation_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS academic_reconciliation_item (
    UUID_ACADEMIC_ITEM CHAR(36) NOT NULL PRIMARY KEY,
    UUID_RUN CHAR(36) NOT NULL,
    ENROLLMENT_KEY VARCHAR(100) NULL,
    SUBJECT_KEY VARCHAR(100) NULL,
    UUID_OPERATION CHAR(36) NULL,
    PRODUCT_EDITION VARCHAR(80) NULL,
    EXTERNAL_SYSTEM VARCHAR(40) NOT NULL,
    EXTERNAL_REFERENCE VARCHAR(120) NULL,
    DIFFERENCE_TYPE VARCHAR(50) NOT NULL,
    SOURCE_SNAPSHOT_HASH CHAR(64) NOT NULL,
    TARGET_SNAPSHOT_HASH CHAR(64) NOT NULL,
    DIFFERENCE_JSON JSON NOT NULL,
    RESOLUTION_STATUS VARCHAR(30) NOT NULL,
    RESOLUTION_ACTION VARCHAR(50) NULL,
    RESOLUTION_RESULT_JSON JSON NULL,
    RESOLVED_BY VARCHAR(100) NULL,
    RESOLVED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_academic_reconciliation_item (UUID_RUN, EXTERNAL_SYSTEM, DIFFERENCE_TYPE, EXTERNAL_REFERENCE),
    KEY idx_academic_reconciliation_status (UUID_RUN, RESOLUTION_STATUS),
    KEY idx_academic_reconciliation_enrollment (ENROLLMENT_KEY, EXTERNAL_SYSTEM),
    CONSTRAINT fk_academic_reconciliation_run
        FOREIGN KEY (UUID_RUN) REFERENCES reconciliation_run(UUID_RUN),
    CONSTRAINT fk_academic_reconciliation_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
