-- Additive checkpoint derived from the content-level functional audit.
-- It deliberately keeps new fiscal columns nullable so existing rows and
-- current writers remain deployable while backfill/validation is pending.

ALTER TABLE factura
    ADD COLUMN EMISSOR_NIF VARCHAR(20) NULL AFTER E_FACT,
    ADD COLUMN EMISSOR_NOM VARCHAR(180) NULL AFTER EMISSOR_NIF,
    ADD COLUMN DESCRIPCIO_OPERACIO VARCHAR(500) NULL AFTER BILLING_EMAIL,
    ADD COLUMN INVERSIO_SUBJECTE_PASSIU TINYINT(1) NOT NULL DEFAULT 0 AFTER IVA_IMPORT,
    ADD COLUMN CAUSA_EXEMPCIO_NO_SUBJECTA VARCHAR(80) NULL AFTER INVERSIO_SUBJECTE_PASSIU,
    ADD COLUMN RECARREC_EQUIVALENCIA_PCT DECIMAL(5,2) NULL AFTER CAUSA_EXEMPCIO_NO_SUBJECTA,
    ADD COLUMN RECARREC_EQUIVALENCIA_IMPORT DECIMAL(12,2) NULL AFTER RECARREC_EQUIVALENCIA_PCT,
    ADD COLUMN SIF_CODE VARCHAR(80) NULL AFTER SOURCE_CHANNEL,
    ADD COLUMN SIF_VERSION VARCHAR(40) NULL AFTER SIF_CODE,
    ADD COLUMN PRODUCTOR_NIF VARCHAR(20) NULL AFTER SIF_VERSION,
    ADD COLUMN GENERATED_TIMEZONE VARCHAR(64) NULL AFTER PRODUCTOR_NIF;

ALTER TABLE factura_linia
    ADD COLUMN INVERSIO_SUBJECTE_PASSIU TINYINT(1) NOT NULL DEFAULT 0 AFTER IVA_IMPORT,
    ADD COLUMN CAUSA_EXEMPCIO_NO_SUBJECTA VARCHAR(80) NULL AFTER INVERSIO_SUBJECTE_PASSIU,
    ADD COLUMN RECARREC_EQUIVALENCIA_PCT DECIMAL(5,2) NULL AFTER CAUSA_EXEMPCIO_NO_SUBJECTA,
    ADD COLUMN RECARREC_EQUIVALENCIA_IMPORT DECIMAL(12,2) NULL AFTER RECARREC_EQUIVALENCIA_PCT;

ALTER TABLE factura_registres
    ADD COLUMN PREV_NUM_FACTURA VARCHAR(30) NULL AFTER HASH_FACT_ANT,
    ADD COLUMN GENERATED_TIMEZONE VARCHAR(64) NULL AFTER PREV_NUM_FACTURA,
    ADD COLUMN SIF_CODE VARCHAR(80) NULL AFTER GENERATED_TIMEZONE,
    ADD COLUMN SIF_VERSION VARCHAR(40) NULL AFTER SIF_CODE,
    ADD COLUMN PRODUCTOR_NIF VARCHAR(20) NULL AFTER SIF_VERSION;

ALTER TABLE fiscal_queue
    ADD COLUMN PAYLOAD_HASH CHAR(64) NULL AFTER PAYLOAD_JSON,
    ADD COLUMN AEAT_CSV VARCHAR(120) NULL AFTER LAST_ERROR,
    ADD COLUMN AEAT_ERROR_CODE VARCHAR(80) NULL AFTER AEAT_CSV,
    ADD COLUMN AEAT_ERROR_MESSAGE VARCHAR(500) NULL AFTER AEAT_ERROR_CODE,
    ADD COLUMN NEXT_RETRY_AT DATETIME NULL AFTER LOCKED_AT,
    ADD COLUMN FLOW_WAIT_SECONDS INT NULL AFTER NEXT_RETRY_AT,
    ADD COLUMN FIRST_SENT_AT DATETIME NULL AFTER FLOW_WAIT_SECONDS,
    ADD COLUMN LAST_SENT_AT DATETIME NULL AFTER FIRST_SENT_AT;

ALTER TABLE factura_documents
    ADD COLUMN STORAGE_REF VARCHAR(255) NULL AFTER PATH_FITXER,
    ADD COLUMN DOCUMENT_VERSION VARCHAR(40) NULL AFTER HASH_FITXER,
    ADD COLUMN QR_URL VARCHAR(500) NULL AFTER DOCUMENT_VERSION,
    ADD COLUMN QR_DATA_HASH CHAR(64) NULL AFTER QR_URL,
    ADD COLUMN VERIFACTU_TEXT VARCHAR(255) NULL AFTER QR_DATA_HASH;

CREATE TABLE IF NOT EXISTS commercial_operation (
    UUID_OPERATION CHAR(36) NOT NULL PRIMARY KEY,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    OPERATION_TYPE VARCHAR(40) NOT NULL,
    SOURCE_CHANNEL VARCHAR(30) NOT NULL,
    SOURCE_TYPE VARCHAR(40) NOT NULL,
    SOURCE_ID VARCHAR(80) NULL,
    PRODUCT_TYPE VARCHAR(40) NOT NULL,
    PRODUCT_CODE VARCHAR(80) NULL,
    PRODUCT_EDITION VARCHAR(80) NULL,
    CLASSIFICATION VARCHAR(40) NOT NULL,
    CLASSIFICATION_REASON VARCHAR(80) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CURRENCY CHAR(3) NOT NULL DEFAULT 'EUR',
    GROSS_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    DISCOUNT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    NET_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    PRICE_SNAPSHOT_JSON JSON NOT NULL,
    CAPACITY_SNAPSHOT_JSON JSON NULL,
    TAX_SNAPSHOT_JSON JSON NOT NULL,
    UUID_INTENT CHAR(36) NULL,
    UUID_FACTURA CHAR(36) NULL,
    UUID_PAYMENT CHAR(36) NULL,
    EXPIRES_AT DATETIME NULL,
    CREATED_BY VARCHAR(100) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_commercial_operation_source (SOURCE_TYPE, SOURCE_ID),
    KEY idx_commercial_operation_classification (CLASSIFICATION, STATUS),
    KEY idx_commercial_operation_invoice (UUID_FACTURA),
    KEY idx_commercial_operation_payment (UUID_PAYMENT),
    CONSTRAINT fk_commercial_operation_invoice
        FOREIGN KEY (UUID_FACTURA) REFERENCES factura(UUID_FACTURA),
    CONSTRAINT fk_commercial_operation_payment
        FOREIGN KEY (UUID_PAYMENT) REFERENCES payment_transaction(UUID_PAYMENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_operation_party (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_OPERATION CHAR(36) NOT NULL,
    PARTY_KEY VARCHAR(100) NOT NULL,
    PARTY_ROLE VARCHAR(30) NOT NULL,
    LEGACY_PERSON_ID BIGINT NULL,
    NIF_CIF VARCHAR(20) NULL,
    NOM_RAO VARCHAR(180) NOT NULL,
    EMAIL VARCHAR(180) NULL,
    PRODUCT_CODE VARCHAR(80) NULL,
    PRODUCT_EDITION VARCHAR(80) NULL,
    LINE_AMOUNT DECIMAL(12,2) NULL,
    SNAPSHOT_JSON JSON NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_commercial_operation_party (UUID_OPERATION, PARTY_KEY, PARTY_ROLE),
    KEY idx_commercial_operation_party_role (PARTY_ROLE, NIF_CIF),
    CONSTRAINT fk_commercial_operation_party_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS discount_validation (
    UUID_VALIDATION CHAR(36) NOT NULL PRIMARY KEY,
    UUID_OPERATION CHAR(36) NOT NULL,
    DISCOUNT_TYPE VARCHAR(40) NOT NULL,
    SUBJECT_PARTY_KEY VARCHAR(100) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    RULE_VERSION VARCHAR(40) NOT NULL,
    RULE_SNAPSHOT_JSON JSON NOT NULL,
    EVIDENCE_STORAGE_REF VARCHAR(255) NULL,
    EVIDENCE_HASH CHAR(64) NULL,
    REQUESTED_AT DATETIME NOT NULL,
    VALIDATED_AT DATETIME NULL,
    VALIDATED_BY VARCHAR(100) NULL,
    REJECTION_REASON VARCHAR(120) NULL,
    RESULT_DISCOUNT_AMOUNT DECIMAL(12,2) NULL,
    FUTURE_ENTITLEMENT_REF VARCHAR(100) NULL,
    IDEMPOTENCY_KEY VARCHAR(140) NOT NULL UNIQUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_discount_validation_operation (UUID_OPERATION),
    KEY idx_discount_validation_status (STATUS, DISCOUNT_TYPE),
    CONSTRAINT fk_discount_validation_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_link (
    UUID_PAYMENT_LINK CHAR(36) NOT NULL PRIMARY KEY,
    UUID_OPERATION CHAR(36) NOT NULL,
    TOKEN_HASH CHAR(64) NOT NULL UNIQUE,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    PAYER_PARTY_KEY VARCHAR(100) NULL,
    EXPECTED_AMOUNT DECIMAL(12,2) NOT NULL,
    CURRENCY CHAR(3) NOT NULL DEFAULT 'EUR',
    EXPIRES_AT DATETIME NOT NULL,
    REVOKED_AT DATETIME NULL,
    REVOKED_BY VARCHAR(100) NULL,
    REVOKE_REASON VARCHAR(120) NULL,
    REPLACED_BY_UUID CHAR(36) NULL,
    LAST_ACCESSED_AT DATETIME NULL,
    CREATED_BY VARCHAR(100) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_payment_link_operation (UUID_OPERATION),
    KEY idx_payment_link_status (STATUS, EXPIRES_AT),
    CONSTRAINT fk_payment_link_operation
        FOREIGN KEY (UUID_OPERATION) REFERENCES commercial_operation(UUID_OPERATION),
    CONSTRAINT fk_payment_link_replacement
        FOREIGN KEY (REPLACED_BY_UUID) REFERENCES payment_link(UUID_PAYMENT_LINK)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
