CREATE TABLE IF NOT EXISTS redsys_callback_queue (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_JOB CHAR(36) NOT NULL UNIQUE,
    NOTIFICATION_ID BIGINT NOT NULL,
    UUID_INTENT CHAR(36) NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'QUEUED',
    ATTEMPTS INT NOT NULL DEFAULT 0,
    AVAILABLE_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOCKED_AT DATETIME NULL,
    LOCKED_BY VARCHAR(100) NULL,
    LAST_ERROR TEXT NULL,
    RESULT_JSON JSON NULL,
    UUID_FACTURA CHAR(36) NULL,
    UUID_PAYMENT CHAR(36) NULL,
    PROCESSED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY uq_redsys_callback_notification (NOTIFICATION_ID),
    KEY idx_redsys_callback_available (STATUS, AVAILABLE_AT),
    KEY idx_redsys_callback_intent (UUID_INTENT),
    CONSTRAINT fk_redsys_callback_notification
        FOREIGN KEY (NOTIFICATION_ID) REFERENCES redsys_notifications(ID),
    CONSTRAINT fk_redsys_callback_intent
        FOREIGN KEY (UUID_INTENT) REFERENCES redsys_payment_intent(UUID_INTENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
