CREATE TABLE IF NOT EXISTS usoc_financing_terms (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID_TERMS CHAR(36) NOT NULL UNIQUE,
    REQUEST_ID VARCHAR(120) NOT NULL UNIQUE,
    ID_INSC BIGINT NOT NULL,
    IDPAG BIGINT NOT NULL,
    STUDENT_AMOUNT DECIMAL(12,2) NOT NULL,
    ENTITY_AMOUNT DECIMAL(12,2) NOT NULL,
    ACTOR_ID VARCHAR(120) NOT NULL,
    ACTOR_ROLES VARCHAR(255) NULL,
    LEGACY_STATE_HASH CHAR(64) NOT NULL,
    PREPARED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_usoc_financing_terms_identity (ID_INSC, IDPAG),
    KEY idx_usoc_financing_terms_prepared (PREPARED_AT),
    CONSTRAINT chk_usoc_financing_terms_student_positive CHECK (STUDENT_AMOUNT > 0),
    CONSTRAINT chk_usoc_financing_terms_entity_positive CHECK (ENTITY_AMOUNT > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
